contrib/go-audit.init
contrib/rh-sysv.go-audit.init

This change adds a SysV-style init script and a systemd service unit configuration to manage go-audit as a service. The SysV init script is useful, in particular, on EL6-based systems (e.g. RHEL 6 and CentOS 6). The systemd service unit configuration can be used on systemd-based systems, including EL7. I have tested these on CentOS 6 and CentOS 7.

Add SysV-style init script and systemd service unit configuration

---

go-audit.yaml.example

Currently, if auditing is not enabled at boot time with the `audit=1` boot parameter, go-audit does not explicitly enable it and thus once started it seems to not work. Although enabling it at boot is the most robust way to do it, it makes sense to have go-audit enable it at runtime just in case. Notably, vanilla `auditd` does this.
I'm not sure how to write a good unit test for an exec command like this so I left that part out. Advice on this would be appreciated if a unit test is necessary.

Enable the audit system when starting

---

.gitignore
contrib/line-parser/README.md
contrib/line-parser/line-parser
contrib/line-parser/package.json

Adds a `line-parser` script to decode `go-audit` output without running `streamstash` as a service

Simple line parser program for go-audit lines

---

README.md
audit.go
audit_test.go
go-audit.yaml.example

Some small re-ordering was necessary to avoid stdout logging.

Add a stdout output

---

audit_test.go

When a Linux user has a full name set, the Go user.Name field returns
the full name, rather than the username. The audit_test uses this
value for the output.file.user config, which causes the test to fail
with an unexpected "Could not find uid for user" error returned by
createFileOutput(). This patch fixes the test to use the Username field
instead of the Name field.
Fixes test on Linux with a full name configured for the current user. Test previously failed with:
```
$ go test -v
=== RUN   Test_loadConfig
--- PASS: Test_loadConfig (0.00s)
=== RUN   Test_setRules
Flushed existing audit rules
Flushed existing audit rules
Flushed existing audit rules
Added audit rule #1
Added audit rule #3
--- PASS: Test_setRules (0.00s)
=== RUN   Test_createFileOutput
--- FAIL: Test_createFileOutput …
```

Fix test usage of user.Name when user has full name set

---

audit.go
audit_test.go
contrib/logrotate.go-audit.conf
go-audit.yaml.example

Currently, when using the file output module, there is no clean way to rotate the log file it produces. This is especially important for audit log messages, which can grow very large over time.
This change will trap a USR1 signal and re-open the log file upon receipt of the signal. The intention is for this to be used along with logrotate. I've also included a sample logrotate configuration that works with it.
I've additionally changed the log file location in the example conf to /var/log/go-audit/go-audit.log, and changed the ownership to root/root (which is important since audit logs often contain sensitive information).

Add support for logfile rotation

---

contrib/go-audit.rpmbuild.spec

This change adds an rpmbuild SPEC file to the contrib folder. It can be used to build RPM packages.
I've tested it on CentOS 6 and CentOS 7. It's designed to support both SysV and systemd-based systems. I haven't tested on Fedora but it should work there too.
This change references the logrotate config currently pending merge in #11.

Add rpmbuild SPEC file for RPM packaging

---

audit.go
audit_test.go
go-audit.yaml.example
marshaller.go
marshaller_test.go

Currently, go-audit filters out all audit messages outside the range
[1300, 1399], which corresponds to kernel-originating events. This diff
changes that range to [1100, 1399] to include "user space trusted
application messages" (see linux/audit.h). These messages include those
sent by PAM when user sessions begin and end.
Below is an example (pretty printed) JSON produced by go-audit for such a message:
```
{
"messages" : [
{
"data" : "pid=13204 uid=0 auid=1000 ses=13 msg='op=login id=1000 exe=\"/usr/sbin/sshd\" hostname=172.18.0.138 addr=172.18.0.138 terminal=/dev/pts/2 res=success'",
"type" : 1112
}
],
"sequence" : 1016534,
"timestamp" : "1485660821.217",
"uid_map" : {
"1000" : "ubuntu",
"0" : "root"
}
}
```
None
Existing tests seem to cover message parsing, and the new messages follow …

Make event range configurable

---

audit.go
client.go
client_test.go

Provides better test-ability and error messages in tests that fail for the NetlinkClient

Slightly better netlink client tests

---

.travis.yml

Older versions of go will break with the syslog output test. This will test against the latest 1 dot minor release.

Use latest 1.x version of go

---

.gitignore
audit.go
audit_test.go
go-audit.yaml.example
vendor/vendor.json

This PR adds GELF logging driver as output option. It provides several features that a simple Syslog message does not. As well as others output the most settings of GELF can be handled on go-audit configuration file.
I ran a fresh Graylog2 stack using docker-compose (see more details at [1]) and added an input UDP on 12201 port. So, I pointed my GELF output into `go-audit.yaml` to my local Graylog2 server and it works. :+1: 
My `docker-compose.yaml` file is:
```
version: '2'
services:
mongo:
image: mongo:3
elasticsearch:
image: docker.elastic.co/elasticsearch/elasticsearch:5.6.12
environment:
- http.host=0.0.0.0
- xpack.security.enabled=false
- "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
ulimits:
memlock:
soft: -1
hard: -1
mem_limit: 2g
graylog:
image: graylog/graylog:3.0
environment:
- …
```

Support GELF logging driver as an output option

---

extras.go

the ExtraParser constructor returns nil if the parser is not enabled, so don't append
it if it is nil.
Fixes #69

only append the ExtraParser if it's non-nill

---

client.go

> Replaces the link that is currently stale for `MAX_AUDIT_MESSAGE_LENGTH` with one tied to a specific linux kernel tag (so the line number remains constant/correct) from the official torvalds linux repo on Github.
> None
> N/A

Replace dead MAX_AUDIT_MESSAGE_LENGTH comment link

---

extras_containers.go
extras_containers_capsule8.go
go.mod

Capsule8 has removed their open source repo:
- https://twitter.com/capsule8/status/1272993092405211136
We only needed one function from here, so we vendor just the stuff we
need for procfs.ProcessContainerID into a new file
extras_containers_capsule8.go (with original LICENSE intact).
Fixes: #78

remove capsule8 dependency

---

.github/workflows/gofmt.yml
.github/workflows/release.yml
.github/workflows/test.yml
CHANGELOG.md
Makefile
audit.go
client.go
extras_containers.go

This change adds a build and release process for go-audit. go-fmt and
tests are run with every commit, and a special release workflow runs
when a version tag is pushed to the repo. This is based on the build process for https://github.com/slackhq/nebula. We currently only build binaries for amd64, but we can easily build for other architectures if there is demand. This also sets up a CHANGELOG
file that we will update with the first tagged release.
Fixes #77 (once a version is tagged after this has been merged).
I tested this on my fork: https://github.com/wadey/go-audit/releases

build and release process

---

README.md

Remove the Travis-CI and Codecov references from the readme since we are
no longer using them.

Remove Travis-CI references from README

---

README.md

> `govendor` is not required after the switch to go modules
> https://github.com/slackhq/go-audit/commit/e90a1ca903c1fb81c0d89da6884eb3a5f16141ec
> this is just a doco update

remove govendor from installation instructions

---

extras_cgroups.go
parser.go

Add a new option `extras.cgroups.enabled` that when enabled will annotate events with the cgroup_v2 root path. 
The primary use-case for this is to be able to correlate related events that share the same cgroup path (such as child processes forked from a systemd unit).

Cgroup extras.

---

extras_containers.go
extras_helpers.go

The extras_containers.go file is only built on amd64. This prevents
the use of this function by the cgroup parser extension on non-amd64
architectures.
Move getPid to helpers file.
The extras_containers.go file is only built on amd64. This prevents
the use of this function by the cgroup parser extension on non-amd64
architectures.
N/A
N/A

Move getPid to helpers file

---

audit.go
audit_test.go

The newer version of viper / mapstructure now loads the "filters" config element as a `[]map[string]interface{}`, so fix our code to deal with that change.

fix for update in viper / mapstructure
